"""Update Tweet content length

Revision ID: 23980e25c105
Revises: 11bd33c60286
Create Date: 2021-11-30 00:34:29.181368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23980e25c105"
down_revision = "11bd33c60286"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
